const meridianPoints = [
  {
    id: 'LU',
    chinese: '手太阴肺经',
    english: 'Lung',
    title: 'Lung',
    korean: '수태음폐경',
    viet: 'Thủ thái âm phế',
    points: [
      {
        id: 'LU-1',
        name: '中府',
        transliteration: 'Zhongfu',
        english: 'Middle Palace',
        pinyin: 'zhōng fǔ',
        korean: 'jung bu 중부',
        romaji: 'chū fu',
        vietnamese: 'Trung phủ',
      },
      {
        id: 'LU-2',
        name: '雲門',
        transliteration: 'Yunmen',
        english: 'Cloud Gate',
        pinyin: 'yún mén',
        korean: 'un mun 운문',
        romaji: 'un mon?',
        vietnamese: 'Vân môn',
      },
      {
        id: 'LU-3',
        name: '天府',
        transliteration: 'Tianfu',
        english: 'Palace of Heaven',
        pinyin: 'tiān fǔ',
        korean: 'cheon bu 천부',
        romaji: 'tem pu(?)',
        vietnamese: '',
      },
      {
        id: 'LU-4',
        name: '俠白',
        transliteration: 'Xiabai',
        english: 'Clasping the White',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-5',
        name: '尺澤',
        transliteration: 'Chize',
        english: 'Cubit Marsh',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-6',
        name: '孔最',
        transliteration: 'Kongzui',
        english: 'Maximum Opening',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-7',
        name: '列缺',
        transliteration: 'Lieque',
        english: 'Broken Sequence',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-8',
        name: '經渠',
        transliteration: 'Jingqu',
        english: 'Channel Gutter',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-9',
        name: '太淵',
        transliteration: 'Jingqu',
        english: 'Supreme Abyss',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-10',
        name: '魚際',
        transliteration: 'Yuji',
        english: 'Fish Border',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
      {
        id: 'LU-11',
        name: '魚際',
        transliteration: 'Shaoshang',
        english: 'Lesser Shang',
        pinyin: '',
        korean: '',
        romaji: '',
        vietnamese: '',
      },
    ],
  },
  {
    id: 'LI',
    chinese: '手阳明大肠经',
    english: 'Large Intestine',
    title: 'Large Intestine',
    korean: '수양명대장경',
    viet: 'Thủ dương minh đại trường',
  },
  {
    id: 'ST',
    chinese: '足阳明胃经',
    english: 'Stomach',
    title: 'Stomach',
    korean: '족양명위경',
    viet: 'Túc dương minh vị',
  },
  {
    id: 'SP',
    chinese: '足太阴脾经',
    english: 'Spleen',
    title: 'Spleen',
    korean: '족태음비경',
    viet: 'Túc thái âm tỳ',
  },
  {
    id: 'HT',
    chinese: '手少阴心经',
    english: 'Heart',
    title: 'Heart',
    korean: '수소음심경',
    viet: 'Thủ thiếu âm tâm',
  },
  {
    id: 'SI',
    chinese: '手太阳小肠经',
    english: 'Small Intestine',
    title: 'Small Intestine',
    korean: '수태양소장경',
    viet: 'Thủ thái dương tiểu trường',
  },
  {
    id: 'BL',
    chinese: '足太阳膀胱经',
    title: 'Bladder',
    english: 'Bladder',
    korean: '족태양방광경',
    viet: 'Túc thái dương bàng quang',
  },
  {
    id: 'KI',
    chinese: '足少阴肾经',
    english: 'Kidney',
    title: 'Kidney',
    korean: '족소음신경',
    viet: 'Túc thiếu âm thận',
  },
  {
    id: 'PC',
    chinese: '手厥阴心包经',
    title: 'Pericardium',
    english: 'Pericardium',
    korean: '수궐음심포경',
    viet: 'Thủ quyết âm tâm bào',
  },
  {
    id: 'TE',
    chinese: '手少阳三焦经',
    english: 'Triple Energizer',
    title: 'Triple Energizer',
    korean: '수소양삼초경',
    viet: 'Thủ thiếu dương tam tiêu',
  },
  {
    id: 'GB',
    chinese: '足少阳胆经',
    title: 'Gallbladder',
    english: 'Gallbladder',
    korean: '족소양담경',
    viet: 'Túc thiếu dương đởm',
  },
  {
    id: 'LV',
    chinese: '足厥阴肝经',
    english: 'Liver',
    title: 'Liver',
    korean: '족궐음간경',
    viet: 'Túc quyết âm can ',
  },
]

export default meridianPoints
